# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'web2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(568, 358)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reload = QtWidgets.QPushButton(self.centralwidget)
        self.reload.setGeometry(QtCore.QRect(390, 170, 80, 26))
        self.reload.setObjectName("reload")
        self.check = QtWidgets.QPushButton(self.centralwidget)
        self.check.setGeometry(QtCore.QRect(220, 210, 80, 26))
        self.check.setObjectName("check")
        self.inputtxt = QtWidgets.QLineEdit(self.centralwidget)
        self.inputtxt.setGeometry(QtCore.QRect(180, 160, 181, 31))
        self.inputtxt.setObjectName("inputtxt")
        self.imgarea = QtWidgets.QLabel(self.centralwidget)
        self.imgarea.setGeometry(QtCore.QRect(180, 60, 191, 61))
        self.imgarea.setText("")
        self.imgarea.setPixmap(QtGui.QPixmap("out.jpg"))
        self.imgarea.setScaledContents(True)
        self.imgarea.setObjectName("imgarea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 568, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reload.setText(_translate("MainWindow", "reload"))
        self.check.setText(_translate("MainWindow", "check"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
